# Generated by Django 4.2.4 on 2023-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('account', models.CharField(max_length=200, verbose_name='account')),
                ('createdAt', models.IntegerField(verbose_name='createdAt')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('method', models.CharField(max_length=200, verbose_name='method')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
                ('type', models.CharField(max_length=200, verbose_name='type')),
                ('link', models.CharField(max_length=200, verbose_name='link')),
            ],
        ),
    ]
